services:
  - type: web
    name: salon-volosy-beauty
    env: python
    region: frankfurt
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: DATABASE_URL
        value: "postgresql://salon_volosy_photo_bazz_user:Sa0KCOH64FxaJV3Bt7VxRMQRDX4F5L6U@dpg-d56fkmer433s73e4mvog-a/salon_volosy_photo_bazz"
      - key: ADMIN_PASSWORD
        value: "admin2026"
      - key: PORT
        value: "10000"
      - key: RENDER_EXTERNAL_URL
        fromService:
          type: web
          name: salon-volosy-beauty
          property: url
    autoDeploy: true
    healthCheckPath: /health
    healthCheckTimeout: 180